// import dove from '../assets/images/dove.jpg'



const productData = [
    {
        id: 1,
        name: "Classic White T-Shirt",
        description: "A versatile and timeless white t-shirt made from 100% cotton.",
        price: 15.99,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSvkjg6h0asIbNQknQ5rX6X7V53u1Nm9a25Cw&s",
        category: "T-Shirts",
        size: ["S", "M", "L", "XL"],
        stock: 50,
        cat: 'Kids',
        color:'white'
    },
    {
        id: 2,
        name: "Blue Denim Jeans",
        description: "Comfortable and stylish blue denim jeans with a classic fit.",
        price: 49.99,
        image: "https://img0.junaroad.com/uiproducts/17827245/zoom_1-1624701856.jpg",
        category: "Jeans",
        size: ["30", "32", "34", "36"],
        stock: 30,
        cat: 'Men',
        color:'blue'
    },
    {
        id: 3,
        name: "Black Leather Jacket",
        description: "A sleek black leather jacket for a bold and edgy look.",
        price: 199.99,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRwwtUkpiHuchbghtoeSpv-PMk10aPmvqCuGg&s",
        category: "Jackets",
        size: ["S", "M", "L", "XL"],
        stock: 10,
        cat: 'Men',
        color:'black'
    },
    {
        id: 4,
        name: "Red Flannel Shirt",
        description: "A warm and cozy red flannel shirt perfect for chilly days.",
        price: 29.99,
        image: "https://lp2.hm.com/hmgoepprod?set=quality%5B79%5D%2Csource%5B%2F6b%2Fec%2F6becf84f5c26f3573a4dfc177db2fc4d0990ddcc.jpg%5D%2Corigin%5Bdam%5D%2Ccategory%5B%5D%2Ctype%5BDESCRIPTIVESTILLLIFE%5D%2Cres%5Bm%5D%2Chmver%5B2%5D&call=url[file:/product/main]",
        category: "Shirts",
        size: ["S", "M", "L", "XL"],
        stock: 20,
        cat: 'Men',
        color:'red'
    },
    {
        id: 5,
        name: "Summer Dress",
        description: "A light and breezy summer dress with a floral pattern.",
        price: 39.99,
        image: "https://imgs7.luluandsky.com/catalog/product/2/3/231LQ52582-SN18-YELLOW_1.jpeg",
        category: "Dresses",
        size: ["S", "M", "L"],
        stock: 25,
        cat: 'Women',
        color:'yellow'
    },
    {
        id: 6,
        name: "Running Shoes",
        description: "Comfortable and durable running shoes for everyday workouts.",
        price: 79.99,
        image: "https://contents.mediadecathlon.com/p2394050/770f477ba47b1e0b2bec45fb3a42b623/p2394050.jpg?format=auto&quality=70&f=650x0",
        category: "Shoes",
        size: ["8", "9", "10", "11"],
        stock: 40,
        cat: 'Men',
        color:'green'
    },
    {
        id: 7,
        name: "Woolen Scarf",
        description: "A soft and warm woolen scarf to keep you cozy in winter.",
        price: 19.99,
        image: "https://3.imimg.com/data3/SE/WQ/MY-3734722/wool-scarf.png",
        category: "Accessories",
        size: ["One Size"],
        stock: 60,
        cat: 'Women',
        color:'blue'
    },
    {
        id: 8,
        name: "Formal Suit",
        description: "A sharp and elegant formal suit for special occasions.",
        price: 299.99,
        image: "https://uniformtailor.in/image/cache/catalog/data/business-suite/Men-suit/formal-grey-business-suit-670x760.png",
        category: "Suits",
        size: ["S", "M", "L", "XL"],
        stock: 15,
        cat: 'Women',
        color:'grey'
    },
    {
        id: 9,
        name: "Orange Hoodie",
        description: "A cozy and stylish orange hoodie perfect for casual wear.",
        price: 29.99,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRC_AUV65PfP71xSWMIbkLLup5sxDZpZ0G62g&s",
        category: "Hoodies",
        size: ["S", "M", "L", "XL"],
        stock: 15,
        cat: 'Men',
        color:'orange'
    },
    {
        id: 10,
        name: "Red Running Shoes",
        description: "Comfortable running shoes in a vibrant red color.",
        price: 69.99,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQiZM43o9QQmBWNf3O6n25_5ObKmZRQQwpVkA&s",
        category: "Shoes",
        size: ["8", "9", "10", "11"],
        stock: 20,
        cat: 'Women',
        color:'red'
    },
    {
        id: 11,
        name: "Purple Raincoat",
        description: "A waterproof purple raincoat to keep you dry in style.",
        price: 49.99,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSd7kfg9RvGEqA_FbcW-t82zH0JlC0q8t01uQ&s",
        category: "Raincoats",
        size: ["S", "M", "L", "XL"],
        stock: 10,
        cat: 'Kids',
        color:"purple"
    },
    {
        id: 12,
        name: "Black Leather Gloves",
        description: "Elegant black leather gloves for a sophisticated look.",
        price: 19.99,
        image: "https://m.media-amazon.com/images/I/61aTSGUynEL._AC_UF894,1000_QL80_.jpg",
        category: "Gloves",
        size: ["S", "M", "L"],
        stock: '30',
        cat: 'Men',
        color:'black'
    },
    {
        id: 13,
        name: "Yellow Summer Dress",
        description: "A light and breezy yellow summer dress with floral patterns.",
        price: 39.99,
        image: "https://i.pinimg.com/736x/c1/62/e7/c162e79d7c460afa5b14ef5cc38d5ba5.jpg",
        category: "Dresses",
        size: ["S", "M", "L"],
        stock: 25,
        cat: 'Women',
        color:'yellow'
    },
    {
        id: 14,
        name: "Vintage Sunglasses",
        description: "Classic vintage sunglasses with UV protection.",
        price: 49.99,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRfdSjDhWCavyRd4vOFNXhiZL8H1c2PpPgjFecV3JD-r1c_N2f8Pv-ix91MeOp1tgfxZuY&usqp=CAU",
        category: "Accessories",
        size: ["One Size"],
        stock: 35,
        cat: 'Men',
        color:'brown'
    },
    {
        id: 15,
        name: "Leather Wallet",
        description: "A stylish leather wallet with multiple compartments.",
        price: 39.99,
        image: "https://assets.ajio.com/medias/sys_master/root/20230816/uu1W/64dc7144eebac147fccb34ba/-473Wx593H-466384381-brown-MODEL.jpg",
        category: "Accessories",
        size: ["One Size"],
        stock: 45,
        cat: 'Men',
        color:'brown'
    },
    {
        id: 16,
        name: "Casual Sneakers",
        description: "Comfortable and trendy casual sneakers for everyday wear.",
        price: 59.99,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSuSFXBeUkGCzfNMM_dOJFs_FvNXB-28bPNEA&s",
        category: "Shoes",
        size: ["8", "9", "10", "11"],
        stock: 50,
        cat: 'Kids',
        color:'grey'
    },
    {
        id: 17,
        name: "Winter Jacket",
        description: "A warm and waterproof winter jacket for cold climates.",
        price: 149.99,
        image: "https://images-cdn.ubuy.co.in/634e333eb6385819841580f6-winter-coats-for-women-hooded-warm.jpg",
        category: "Jackets",
        size: ["S", "M", "L", "XL"],
        stock: 20,
        cat: 'Women',
        color:'pink'
    },
    {
        id: 18,
        name: "Striped Sweater",
        description: "A stylish striped sweater made from soft cotton blend.",
        price: 34.99,
        image: "https://m.media-amazon.com/images/I/81ZBbneeXfL._AC_UY1100_.jpg",
        category: "Sweaters",
        size: ["S", "M", "L"],
        stock: 30,
        cat: 'Men',
        color:'grey'
    },
    {
        id: 19,
        name: "Leather Belt",
        description: "High-quality leather belt with a classic buckle.",
        price: 24.99,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT3xfi4PGH3RpshWyZcwO0_9YOaIntLra2b_w&s",
        category: "Accessories",
        size: ["S", "M", "L", "XL"],
        stock: 40,
        cat: 'Men',
        color:'brown'
    },
    {
        id: 20,
        name: "Formal Dress Shirt",
        description: "A crisp white dress shirt for formal occasions.",
        price: 49.99,
        image: "https://rukminim2.flixcart.com/image/850/1000/krz97rk0/shirt/j/3/w/s-kfwshirt021-kicky-original-imag5nfnkmm3jf29.jpeg?q=90&crop=false",
        category: "Shirts",
        size: ["S", "M", "L", "XL"],
        stock: 25,
        cat: 'Men',
        color:'white'
            },
    {
        id: 21,
        name: "Denim Skirt",
        description: "A trendy denim skirt with a flattering fit.",
        price: 29.99,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQgRwl1dilL1o9SPODxIzhy1oTAZFbFYBMPVQ&s",
        category: "Skirts",
        size: ["S", "M", "L"],
        stock: 35,
        cat: 'Women',
        color:'silver'
    },
    {
        id: 22,
        name: "Designer Watch",
        description: "Luxurious designer watch with a stainless steel strap.",
        price: 199.99,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRywXjR46wSu6zwitJyhx4fBzJYXqtW_Q43uvp9wed9b2K6rstGw2-QGpk_Q9BgtGm1-nU&usqp=CAU",
        category: "Accessories",
        size: ["One Size"],
        stock: 15,
        cat: 'Men',
        color:'grey'
    },
    {
        id: 23,
        name: "Cotton Polo Shirt",
        description: "A comfortable cotton polo shirt for casual outings.",
        price: 27.99,
        image: "https://www.mystore.in/s/62ea2c599d1398fa16dbae0a/656f25e5ae8e3c47ab094742/t-shirt-for-men-grey-420x420.jpg",
        category: "Shirts",
        size: ["S", "M", "L", "XL"],
        stock: 40,
        cat: 'Men',
        color:'brown'
    },
    {
        id: 24,
        name: "Leather Backpack",
        description: "Spacious leather backpack with adjustable straps.",
        price: 79.99,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQPukFi_xuYiSIwMpUGBGB6Lg1B_6bimPI6Pw&s",
        category: "Bags",
        size: ["One Size"],
        stock: 20,
        cat: 'Kids',
        color:'brown'
    },
   
];

export default productData